config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'

  get '/home/about' => 'homes#about'
  devise_for :users
  resources :books
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  Refile.secret_key = '4769bf095da1f95f449fc9470174f3a73c2f9645138bce2bdb5cb8e3dadfb8b2a2bf89a3b0af6178308565d4224f97f226fdf46e08e5238a24511faece58ef77'
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @books = Book.page(params[:page]).reverse_order
    @book = Book.new
    @user = current_user
  end
  def new

  end
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @books = Book.page(params[:page]).reverse_order
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book)
    else
      render :index
    end
  end
  def show
    @detailed_book = Book.find(params[:id])
    @book = Book.new
    @user = @detailed_book.user
  end
  def edit
    @book = Book.find(params[:id])
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      flash[:alert] = "権限がありません"
      redirect_to books_path
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end
  def about

  end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit,:update]

  def index
    @users = User.page(params[:page]).reverse_order
    @user = current_user
    @book = @user.books.new
  end
  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book = @user.books.new
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
  def ensure_correct_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      flash[:alert] = "権限がありません"
      redirect_to user_path(current_user.id)
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Editing Book</h1>
  <% if @book.errors.any? %>
  <div id="error_explanation">
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <%= form_for(@book) do |f| %>
    <div class="field row">
      <h4>Title</h4>
      <%= f.text_field :title, class:"col-xs-12 book_title" %>
    </div>
    <div class="field row">
      <h4>Body</h4>
      <%= f.text_area :body, class:"col-xs-12 book_body" %>
      <%= f.submit 'Update Book', class:"btn btn-primary col-xs-12" %>
    </div>
  <% end %>
  <div class="actions row">
    <%= link_to "Show", book_path(@book), class:"book_19691" %>
  </div>
  <%= link_to "Back", books_path, class:"back" %>
</div>
<div class="col-md-3"></div>

app/views/books/index.html.erb
<%= render 'shared/common', book: @book, user: @user %>

<div class='col-xs-9'>
  <h2>Books</h2>

  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to "/users/#{book.user.id}" do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class:"attachment user profile_image fallback" , fallback: "no_image.jpg" %>
            <% end %>
          </td>
          <td><%= link_to book.title, book_path(book) %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
      <%= paginate @books, class: "paginate" %>
    </tbody>
  </table>
</div>

app/views/books/show.html.erb
<%= render 'shared/common', book: @book, user: @user %>

<div class='col-xs-9'>
  <h2>Book detail</h2>

  <table class='table'>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
        <tr>
            <td>
              <%= attachment_image_tag @detailed_book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class:"attachment user profile_image fallback" , fallback: "no_image.jpg" %><br>
              <%= link_to @detailed_book.user.name, user_path(@detailed_book.user) %>
            </td>
            <td><%= link_to @detailed_book.title, book_path(@detailed_book) %></td>
            <td><%= @detailed_book.body %></td>
          <% if current_user.id == @detailed_book.user_id %>
            <td><%= link_to "Edit", edit_book_path(@detailed_book), class: "btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@detailed_book), method: :delete, data: {confirm: "本当に消しますか？"},class: "btn-sm btn-danger" %></td>
          <% end %>
        </tr>
    </tbody>
  </table>
</div>

app/views/books/top.html.erb
<div class='body'>
  <div class='container'>
    <p id="notice"></p>
    <div class="row">
      <div class='top-message col-md-offset-3 col-md-6'>
        <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
          <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>
          <div class="btn-wrapper">
            <div class="row">
              <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
            </div>
            <div class="row">
              <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/homes/about.html.erb
<h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>

app/views/homes/top.html.erb
<div class='top-message col-md-offset-3 col-md-6'>
  <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
    <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
        <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
      </div>
      <div class="row">
        <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookers2</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav class="nav navbar-nav navbar-left" >
        <span>Bookers</span>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li>
            <%= link_to 'Home', user_path(current_user.id), class: "glyphicon glyphicon-home home" %>
          </li>
          <li class="">
            <%= link_to 'Users', users_path, class: "glyphicon glyphicon-user users" %>
          </li>
          <li class="">
            <%= link_to 'Books', books_path, class: "glyphicon glyphicon-book books" %>
          </li>
          <li class="">
            <%= link_to "logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %>
          </li>
          <% else %>
          <li><%= link_to "Home" , root_path, class: "glyphicon glyphicon-home home" %></li>
          <li><%= link_to "About", "/home/about", class: "glyphicon glyphicon-link about" %></li>
          <li class="">
            <%= link_to "sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %>
          </li>
          <li class="">
            <%= link_to "login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %>
          </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
  <div class="body">
    <div class="container">
      <% if flash[:notice] %>
          <p id="notice">
            <%= flash[:notice] %>
          </p>
        <% end %>
        <% if flash[:alert] %>
          <p id="alert">
            <%= flash[:alert] %>
          </p>
        <% end %>
        <div class="row">
          <%= yield %>
        </div>
    </div>
  </div>
  <footer>
    <div class='container'>
      <div class='row'>
        <div class='col-xs-3 col-xs-offset-9'>
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/shared/_common.html.erb
<% if book.errors.any? %>
<div id="error_explanation">
  <h3><%= book.errors.count %> errors prohibited this obj from being saved</h3>
  <ul>
    <% book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class='col-xs-3'>
  <h2>User info</h2>
  <table class='table'>
    <tr>
      <%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, format: 'jpeg', class:"attachment user profile_image fallback" , fallback: "no_image.jpg" %>
    </tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </table>

  <div class='row'>
    <%= link_to "", edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
  </div>

  <%= form_for(@book) do |f| %>
  <h2>New book</h2>
  <div class="field row">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class:"col-xs-12 book_title" %>
  </div>
  <div class="field row">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class:"col-xs-12 book_body", rows:"3" %>
  </div>
  <div class="actions row">
    <%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
  </div>
  <% end %>

</div>

app/views/users/edit.html.erb
<h2>User info</h2>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h3><%= @user.errors.count %> errors prohibited this obj from being saved</h3>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= form_for(@user) do |f| %>
<div class="field">
  <label for="user_name">Name</label>
  <%= f.text_field :name, autofocus: true, class:"name", id:"user_name", placeholder:"#{@user.name}" %>
  <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
</div>
<div class="field">
  <label for="user_image">Image</label>
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "user_image", fallback: "no_image.jpg" %>
  <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
</div>
<div class="field">
  <label for="user_introduction">Introduction</label>
  <%= f.text_area :introduction, class:"introduction" %>
</div>
<div class="actions">
<%= f.submit "Update User" %>
</div>
<% end %>

app/views/users/index.html.erb
<%= render 'shared/common', book: @book, user: @user %>

<div class='col-xs-9'>
  <h2>Users</h2>

  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th></th>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', class:"attachment user profile_image fallback" , fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      <% end %>
      <%= paginate @users, class: "paginate" %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<%= render 'shared/common', book: @book, user: @user %>

<div class='col-xs-9'>
  <h2>Books</h2>

  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td><%= attachment_image_tag current_user, :profile_image, :fill, 40, 40, format: 'jpeg', class:"attachment user profile_image fallback" , fallback: "no_image.jpg" %></td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
      </tr>
      <% end %>
      <%= paginate @books, class: "paginate" %>
    </tbody>
  </table>
</div>